<?php

namespace ContainerI5jMFkA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuteurController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Frontend\AuteurController' shared autowired service.
     *
     * @return \App\Controller\Frontend\AuteurController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Frontend/AuteurController.php';

        $container->services['App\\Controller\\Frontend\\AuteurController'] = $instance = new \App\Controller\Frontend\AuteurController(($container->privates['App\\Repository\\AuteurRepository'] ?? $container->load('getAuteurRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Frontend\\AuteurController', $container));

        return $instance;
    }
}
