<?php

namespace ContainerI5jMFkA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Frontend\LivreController' shared autowired service.
     *
     * @return \App\Controller\Frontend\LivreController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Frontend/LivreController.php';

        $container->services['App\\Controller\\Frontend\\LivreController'] = $instance = new \App\Controller\Frontend\LivreController(($container->privates['App\\Repository\\LivreRepository'] ?? $container->load('getLivreRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Frontend\\LivreController', $container));

        return $instance;
    }
}
