<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL7Mv7t7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL7Mv7t7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL7Mv7t7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL7Mv7t7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL7Mv7t7\App_KernelDevDebugContainer([
    'container.build_hash' => 'L7Mv7t7',
    'container.build_id' => 'fb7c6511',
    'container.build_time' => 1701330066,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL7Mv7t7');
